# Generated by Django 2.1.1 on 2018-09-23 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noah_core', '0008_hubmodel_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationmodel',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='noah_core.StatusModel'),
        ),
    ]
