# Generated by Django 2.1.1 on 2018-09-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noah_core', '0009_donationmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmodel',
            name='code',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='statusmodel',
            name='label',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
