# Generated by Django 2.1.1 on 2018-09-23 09:17

from django.db import migrations
from django.utils.text import slugify


def create_statuses(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    StatusModel = apps.get_model('noah_core', 'StatusModel')
    # Keeping gaps between status numbers of consecutive create_statuses
    # so that new statuses can be created at any position in the future.
    statuses = [
        {'status': 20, 'label': 'Submitted by Donor',},
        {'status': 30, 'label': 'Received at collection hub',},
        {'status': 40, 'label': 'Rejected',},
        {'status': 50, 'label': 'Ready for Delivery',},
        {'status': 60, 'label': 'To Repair',},
        {'status': 70, 'label': 'Scrap',},
        {'status': 80, 'label': 'Out for Delivery',},
        {'status': 90, 'label': 'Collected from Hub',},
        {'status': 100, 'label': 'Delivered',},
    ]
    for s in statuses:
        s['code'] = slugify(s['label'])
        obj, created = StatusModel.objects.get_or_create(
            status=s['status'],
            defaults=s
        )
class Migration(migrations.Migration):

    dependencies = [
        ('noah_core', '0010_auto_20180923_0842'),
    ]

    operations = [
        migrations.RunPython(create_statuses,
                             reverse_code=migrations.RunPython.noop),
    ]
